#!/bin/bash
set -euo pipefail

# ---------------------------------------------------------------------------
# AVA EC2 Setup Script
#
# Usage: sudo -u ubuntu bash setup_ava.sh <GITHUB_PAT> <SOMETHINGS_DB_PASSWORD>
#
# Before running, create /opt/ava/.env.secrets with sensitive values:
#   VERTEX_AI_SERVICE_ACCOUNT_KEY='{"type":"service_account",...}'
#   SLACK_BOT_TOKEN=xoxb-...
#   SLACK_SIGNING_SECRET=...
#   OPENAI_API_KEY=sk-...          (optional)
#   ANTHROPIC_API_KEY=sk-ant-...   (optional)
#   BRAVE_API_KEY=BSA...           (optional)
#
# The script pulls RDS passwords from SSM and looks up endpoints automatically.
# ---------------------------------------------------------------------------

if [ $# -lt 1 ]; then
  echo "Usage: $0 <GITHUB_PAT> [SOMETHINGS_DB_PASSWORD]"
  echo "  GITHUB_PAT:            Fine-grained PAT with read access to Somethings org repos"
  echo "  SOMETHINGS_DB_PASSWORD: (optional) Somethings production RDS password"
  echo ""
  echo "Requires /opt/ava/.env.secrets with VERTEX_AI_SERVICE_ACCOUNT_KEY, SLACK_BOT_TOKEN, SLACK_SIGNING_SECRET"
  exit 1
fi

GITHUB_PAT="$1"
APP_DIR="/opt/ava"
REPO_URL="https://github.com/Somethings/ava-agent.git"
SECRETS_FILE="${APP_DIR}/.env.secrets"

echo "=== AVA Setup Script ==="

# Check secrets file exists
if [ ! -f "${SECRETS_FILE}" ]; then
  echo "ERROR: ${SECRETS_FILE} not found."
  echo "Create it with at minimum:"
  echo "  VERTEX_AI_SERVICE_ACCOUNT_KEY='...'"
  echo "  SLACK_BOT_TOKEN=..."
  echo "  SLACK_SIGNING_SECRET=..."
  exit 1
fi

# Source secrets
set -a
source "${SECRETS_FILE}"
set +a

# Validate required secrets
for var in VERTEX_AI_SERVICE_ACCOUNT_KEY SLACK_BOT_TOKEN SLACK_SIGNING_SECRET; do
  if [ -z "${!var:-}" ]; then
    echo "ERROR: ${var} not set in ${SECRETS_FILE}"
    exit 1
  fi
done

# ---------------------------------------------------------------------------
# 1. Git credentials
# ---------------------------------------------------------------------------
echo "[1/7] Configuring git credentials..."
git config --global url."https://${GITHUB_PAT}@github.com/".insteadOf "https://github.com/"
git config --global user.name "AVA Agent"
git config --global user.email "ava@somethings.com"

# ---------------------------------------------------------------------------
# 2. Clone repo
# ---------------------------------------------------------------------------
echo "[2/7] Cloning ava-agent repo..."
if [ -d "${APP_DIR}/.git" ]; then
  echo "  Repo already exists, pulling latest..."
  cd "${APP_DIR}"
  git pull
else
  cd "${APP_DIR}"
  git clone "${REPO_URL}" .
fi

# ---------------------------------------------------------------------------
# 3. Install dependencies
# ---------------------------------------------------------------------------
echo "[3/7] Installing dependencies..."
cd "${APP_DIR}"
pnpm install --frozen-lockfile

# ---------------------------------------------------------------------------
# 4. Generate .env
# ---------------------------------------------------------------------------
echo "[4/7] Generating .env..."

# URL-encode helper (handles special chars in passwords)
urlencode() {
  python3 -c "import urllib.parse, sys; print(urllib.parse.quote(sys.argv[1], safe=''))" "$1"
}

# Pull AVA RDS info from SSM
AVA_RDS_PASSWORD_PARAM=$(aws ssm get-parameter \
  --name "/somethings/production/ava/rds/password_param" \
  --query "Parameter.Value" --output text --region us-east-1)

AVA_RDS_PASSWORD=$(aws ssm get-parameter \
  --name "${AVA_RDS_PASSWORD_PARAM}" \
  --with-decryption --query "Parameter.Value" --output text --region us-east-1)

AVA_RDS_ENDPOINT=$(aws ssm get-parameter \
  --name "/somethings/production/ava/rds/endpoint" \
  --query "Parameter.Value" --output text --region us-east-1)

AVA_RDS_PASSWORD_ENC=$(urlencode "${AVA_RDS_PASSWORD}")

# Somethings prod RDS (old infra, not in SSM — look up directly)
SOMETHINGS_RDS_ENDPOINT=$(aws rds describe-db-instances \
  --db-instance-identifier somethings \
  --query "DBInstances[0].Endpoint.Address" --output text --region us-east-1)

# Somethings prod RDS password
if [ -n "${SOMETHINGS_DB_PASSWORD:-}" ]; then
  SOMETHINGS_RDS_PASSWORD="${SOMETHINGS_DB_PASSWORD}"
elif [ $# -ge 2 ]; then
  SOMETHINGS_RDS_PASSWORD="$2"
else
  echo "  Warning: Somethings prod DB password not provided."
  echo "  Pass as second argument or set SOMETHINGS_DB_PASSWORD in .env.secrets"
  SOMETHINGS_RDS_PASSWORD=""
fi

SOMETHINGS_RDS_PASSWORD_ENC=$(urlencode "${SOMETHINGS_RDS_PASSWORD}")

cat > "${APP_DIR}/.env" <<ENVEOF
# AVA Production Environment (auto-generated by setup_ava.sh)

# Database (AVA's own RDS)
DATABASE_URL=postgresql://ava:${AVA_RDS_PASSWORD_ENC}@${AVA_RDS_ENDPOINT}:5432/ava?sslmode=require&uselibpqcompat=true

# LLM Configuration
LLM_PROVIDER=vertex
LLM_MODEL=claude-opus-4-6
LLM_FALLBACK_MODEL=gemini-2.5-pro

# Vertex AI
VERTEX_AI_PROJECT_ID=link-backend-db8af
VERTEX_AI_LOCATION=us-central1
VERTEX_AI_SERVICE_ACCOUNT_KEY='${VERTEX_AI_SERVICE_ACCOUNT_KEY}'

# API Server
PORT=3001
GATEWAY_PORT=18789
API_PREFIX=/api/ava
NODE_ENV=production

# Security
JWT_SECRET=$(openssl rand -hex 32)

# CORS
ALLOWED_ORIGINS=https://ava.somethings.com

# Context Management
MAX_CONTEXT_TOKENS=100000
COMPACTION_THRESHOLD=0.8
MAX_MESSAGES_PER_SESSION=500

# SQL Tool
SQL_QUERY_TIMEOUT_MS=30000
SQL_MAX_ROWS=1000

# Memory System
EMBEDDING_MODEL=text-embedding-004
MEMORY_SEARCH_LIMIT=10
MEMORY_MIN_SCORE=0.7

# Logging
LOG_LEVEL=info

# Slack Integration
SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}

# Browser Sandbox
BROWSER_MODE=sandbox
BROWSER_CDP_URL=http://localhost:9222

# Somethings Production DB (named database: "somethings")
SOMETHINGS_DB_URL=postgresql://somethings:${SOMETHINGS_RDS_PASSWORD_ENC}@${SOMETHINGS_RDS_ENDPOINT}:5432/production?sslmode=require&uselibpqcompat=true
ENVEOF

# Append optional keys from secrets if present
for var in OPENAI_API_KEY ANTHROPIC_API_KEY BRAVE_API_KEY; do
  if [ -n "${!var:-}" ]; then
    echo "${var}=${!var}" >> "${APP_DIR}/.env"
  fi
done

chmod 600 "${APP_DIR}/.env"
echo "  .env generated successfully"

# ---------------------------------------------------------------------------
# 5. Database migrations + pgvector
# ---------------------------------------------------------------------------
echo "[5/7] Running database migrations..."
cd "${APP_DIR}"

# Install pgvector extension
PGPASSWORD="${AVA_RDS_PASSWORD}" psql \
  "postgresql://ava@${AVA_RDS_ENDPOINT}:5432/ava?sslmode=require" \
  -c "CREATE EXTENSION IF NOT EXISTS vector;" 2>/dev/null || \
  echo "  Note: pgvector extension may already exist or psql not available — run manually if needed"

# Run drizzle migrations
node --import tsx node_modules/drizzle-kit/bin.cjs push || {
  echo "  db:push failed — you may need to run manually: node --import tsx node_modules/drizzle-kit/bin.cjs push"
}

# ---------------------------------------------------------------------------
# 6. Build Docker sandbox images
# ---------------------------------------------------------------------------
echo "[6/7] Building Docker sandbox images..."
if command -v docker &>/dev/null; then
  docker build -t ava-sandbox -f "${APP_DIR}/Dockerfile.sandbox" "${APP_DIR}" || echo "  Warning: sandbox build failed"
  docker build -t ava-browser-sandbox -f "${APP_DIR}/Dockerfile.sandbox-browser" "${APP_DIR}" || echo "  Warning: browser sandbox build failed"
else
  echo "  Docker not available, skipping sandbox builds"
fi

# ---------------------------------------------------------------------------
# 7. Systemd service
# ---------------------------------------------------------------------------
echo "[7/7] Configuring systemd service..."

NPXPATH=$(which npx)

sudo tee /etc/systemd/system/ava.service > /dev/null <<SVCEOF
[Unit]
Description=AVA Agent
After=network.target docker.service
Requires=docker.service

[Service]
Type=simple
User=ubuntu
Group=ubuntu
WorkingDirectory=${APP_DIR}
EnvironmentFile=${APP_DIR}/.env
ExecStart=${NPXPATH} tsx src/index.ts
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=ava
KillSignal=SIGTERM
TimeoutStopSec=15
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
SVCEOF

sudo systemctl daemon-reload
sudo systemctl enable ava
sudo systemctl restart ava

echo ""
echo "=== AVA Setup Complete ==="
echo ""
echo "Check status:  sudo systemctl status ava"
echo "View logs:     journalctl -u ava -f"
echo "Health check:  curl http://localhost:3001/health"
echo ""
echo "Next steps:"
echo "  1. Add DNS CNAME: ava.somethings.com -> <ALB_DNS>"
echo "  2. Update Slack event URL to: https://ava.somethings.com/api/ava/slack/events"
